events {}

http {
    server {
        listen 80;

        # 1. Adiciona o resolvedor de DNS interno do Docker.
        # O Nginx irá usar este endereço para descobrir os containers.
        resolver 127.0.0.11 valid=1s;

        # 2. Cria uma variável para o nome do serviço.
        # Usar uma variável aqui força o Nginx a re-resolver o DNS.
        set $backend_service "webapp";

        location / {
            # 3. Usa a variável para que o Nginx encontre TODOS os containers
            # do serviço 'webapp' e distribua o tráfego entre eles.
            proxy_pass http://$backend_service:5000;
        }
    }
}